/** Shared literal colors for CSS, lightweight-charts, and server-rendered cards. */
const colors = {
  bg: "#08080a",
  panel: "#0e0e11",
  panelInset: "#0b0b0e",
  panelRaised: "#101014",
  panelHover: "#121216",
  surface3: "#131317",
  surface4: "#17171c",
  surface5: "#1c1c22",
  surface6: "#1e1e25",
  line: "#1a1a1f",
  lineStrong: "#22222a",
  lineHover: "#33333d",
  lineRaised: "#26262e",
  lineActive: "#2a2a33",
  lineBright: "#3a3a44",
  text: "#f2f2f5",
  text2: "#b4b4be",
  text3: "#9a9aa4",
  muted: "#8a8a94",
  faint: "#7a7a85",
  // Tailwind v4's lime-300 and lime-950: the design export names no lime.
  accent: "#bbf451",
  accentDeep: "#192e03",
  up: "#3fd68c",
  upSoft: "#7fd9a6",
  upBg: "#06120d",
  down: "#ff6169",
  warn: "#e0b45c",
  warnBright: "#ffc94d",
  warnBg: "#4a3a16",
} as const;

export const visualTheme = {
  ...colors,
  upVolume: `${colors.up}55`,
  downVolume: `${colors.down}55`,
} as const;

/**
 * The identity tint where no image exists: a hue drawn from the address, on
 * the design's fixed saturation and lightness steps, so every wallet and token
 * carries its own colour rather than the accent. Shared so the browser tile
 * and any server-rendered card agree.
 */
export function identityTint(address: string) {
  const hue = (parseInt(address.slice(2, 8), 16) || 0) % 360;
  return {
    background: `hsl(${hue} 42% 13%)`,
    foreground: `hsl(${hue} 78% 72%)`,
  };
}

/** Matches Tailwind's named color utilities while keeping the source JS-friendly. */
export function renderVisualThemeCss() {
  const declarations = Object.entries(visualTheme).map(([name, color]) => {
    const token = name.replace(/([A-Z]|\d+)/g, "-$1").toLowerCase();
    return `  --color-${token}: ${color};`;
  });
  return [
    "/* Generated by scripts/sync-visual-theme.ts. Edit packages/core/src/visual-theme.ts. */",
    "@theme static {",
    ...declarations,
    "}",
    "",
  ].join("\n");
}
